name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: PKHeX.sln                         # Your solution file name
      Test_Project_Path: XGC_PKHeX/Tests/PKHeX.Core.Tests/PKHeX.Core.Tests.csproj # Path to your test project

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: List files at the root
      run: dir  # Lists all files and folders in the root of the repository

    - name: List directories in the root
      run: dir /ad  # Lists only directories in the root

    - name: List contents of XGC_PKHeX
      run: dir XGC_PKHeX  # Lists contents of the XGC_PKHeX directory

    - name: List contents of XGC_PKHeX/Tests
      run: dir XGC_PKHeX/Tests  # Lists contents of the Tests directory

    - name: List contents of XGC_PKHeX/Tests/PKHeX.Core.Tests
      run: dir XGC_PKHeX/Tests/PKHeX.Core.Tests  # Lists contents of the PKHeX.Core.Tests directory

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }}

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ${{ github.workspace }}/bin/${{ matrix.configuration }}  # Adjust path if needed
