name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: List all files and directories
      run: Get-ChildItem -Recurse | Select-Object FullName  # List all files and directories recursively

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test Tests/PKHeX.Core.Tests/PKHeX.Core.Tests.csproj

    - name: Restore the application
      run: msbuild PKHeX.sln /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ${{ github.workspace }}/bin/${{ matrix.configuration }}  # Adjust path if needed
